pgpool check

diff --git a/roles/icinga-client/files/pgpool/check_pgpoolII b/roles/icinga-client/files/pgpool/check_pgpoolII
--- a/roles/icinga-client/files/pgpool/check_pgpoolII
+++ b/roles/icinga-client/files/pgpool/check_pgpoolII
@@ -10,21 +10,92 @@
 
 # get arguments
 
-while getopts 'w:c:hpHUPf:d:b:' OPT; do
-  case $OPT in
-    w)  int_warn=$OPTARG;;
-    c)  int_crit=$OPTARG;;
-    h)  hlp="yes";;
-    p)  perform="yes";;
-    H)  host=$OPTARG;;
-    U)  user=$OPTARG;;
-    P)  port=$OPTARG;;
-    f)  pcpfile=$OPTARG;;
-    d)  pcpdir=$OPTARG;;
-    b)  backendid=$OPTARG;;
-    *)  unknown="yes";;
+set -o errexit -o noclobber -o nounset -o pipefail
+OPTS=$(getopt -o hpH:U:P:w:c:f:d:b: -l help,perfdata,host,user,port,warning:,critical:,pcpfile:,pcpdir:,backendid: --name "$0" -- "$@")
+
+if [ $? != 0 ] ; then echo "Failed parsing options." >&2 ; exit 1 ; fi
+
+echo "$OPTS"
+eval set -- "$OPTS"
+
+perform=false
+hlp=false
+host="localhost"
+user="pgpool"
+port=9898
+int_warn=1
+int_crit=2
+pcpfile=""
+pcpdir="test"
+backendid=0
+
+while true; do
+  case "$1" in
+    -h|--help)  
+        hlp=true
+        shift
+        shift
+        ;;
+    -p|--perdata)
+        perform=true
+        shift
+        shift
+        ;;
+    -H|--host)
+        host=$2
+        shift
+        shift
+        ;;
+    -U|--user)
+        user=$2
+        shift
+        shift
+        ;;
+    -P|--port)
+        port=$2
+        shift
+        shift
+        ;;
+    -w|--warning)
+        int_warn=$2
+        shift
+        shift
+        ;;
+    -c|--critical)
+        int_crit=$2
+        shift
+        shift
+        ;;
+    -f|--pcpfile)
+        pcpfile=$2
+        shift
+        shift
+        ;;
+    -d|--pcpdir)
+        pcpdir=$2
+        shift
+        shift
+        ;;
+    -b|--backendid)
+        backendid=$2
+        shift
+        shift
+        ;;
+    -- ) 
+        shift; 
+        break 
+        ;;
+    *)  
+        echo "Not implemented: $1" >&2
+        exit 1
+        ;;
   esac
 done
+
+echo "$host"
+echo "$pcpfile"
+echo "$pcpdir"
+echo "$backendid"
 
 # usage
 HELP="
@@ -32,22 +103,22 @@ HELP="
 
     syntax:
 
+            -p --> print out performance data
+            -h --> print this help screen
+            -H --> hostname of the pgpool instance
+                   Default hostname is localhost
+            -U --> user to connect to pgpool
+                   Default user is pgpool
+            -P --> pcp port of pgpool pcp
+                   Default port is 9898
             -w --> Warning integer value
             -c --> Critical integer value
-            -P --> print out performance data
-            -H --> print this help screen
-            -h --> hostname of the pgpool instance
-                   Default hostname is localhost
-            -u --> user to connect to pgpool
-                   Default user is pgpool
-            -p --> pcp port of pgpool pcp
-                   Default port is 9898
             -f --> file which contains pcp password
             -b --> backend ID for pgpool backend connection postgres
             -d --> pcp directory file which contain the binaries
 "
 #Check Arguments and exit if they are not set
-if [ "$hlp" = "yes" -o $# -lt 1 ]; then
+if [ "$hlp" = "yes" ]; then
   echo "$HELP"
   exit 0
 fi
@@ -82,6 +153,8 @@ fi
 export PCPPASSFILE=$pcpfile
 
 function pcp_node_info {
-  pcpresult=$($pcpdir"/pcp_node_info -h "$host" -u "$username" -p "$port" "$backendid)
+  pcpresult=$($pcpdir"/pcp_node_info -h "$host" -u "$user" -p "$port" "$backendid)
   echo $pcpresult
 }
+
+pcp_node_info
